# Generated by Django 4.1.7 on 2023-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
